"""The daily note to yourself.

An automated job search that runs quietly is indistinguishable from one that has
broken. This composes a short summary of what actually happened and what needs a
decision, and emails it to the applicant.

Plain text on purpose: it has to be readable on a phone, in a notification
preview, without images loading.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from ..util import env
from ..util.style import sanitise


def _line(label: str, value: Any) -> str:
    """A dot leader rather than padded spaces.

    The house style guard collapses runs of spaces, which is right for prose and
    wrong for a column, so the alignment is drawn with characters that survive it.
    """
    label = f"{label} "
    return f"  {label}{'.' * max(2, 26 - len(label))} {value}"


def compose(stats: dict[str, Any], detail: dict[str, Any], name: str = "") -> tuple[str, str]:
    """Return (subject, body) for the digest."""
    today = datetime.now(timezone.utc).strftime("%A %d %B")
    drafts = stats.get("applications_by_status", {}).get("draft", 0)
    approved = stats.get("applications_by_status", {}).get("approved", 0)
    sent_today = stats.get("sent_today", 0)
    replies = detail.get("new_replies", 0)
    needs_you = detail.get("needs_you", [])

    headline_bits = []
    if sent_today:
        headline_bits.append(f"{sent_today} sent")
    if replies:
        headline_bits.append(f"{replies} repl{'y' if replies == 1 else 'ies'}")
    if drafts:
        headline_bits.append(f"{drafts} to review")
    headline = ", ".join(headline_bits) or "nothing new"

    subject = f"JobSeeker: {headline}, {today}"

    parts = [
        f"Hello{' ' + name if name else ''},",
        "",
        f"Here is where your search stands on {today}.",
        "",
        "TODAY",
        _line("Applications sent", f"{sent_today} of {stats.get('daily_cap', 0)}"),
        _line("New replies", replies),
        _line("Roles discovered", detail.get("discovered", 0)),
        _line("Drafts written", detail.get("drafted", 0)),
        "",
        "WAITING FOR YOU",
        _line("Drafts to review", drafts),
        _line("Approved, not yet sent", approved),
        _line("Replies to answer", detail.get("replies_to_answer", 0)),
        "",
        "OVERALL",
        _line("Roles tracked", stats.get("jobs_total", 0)),
        _line("Shortlisted", stats.get("jobs_by_status", {}).get("shortlisted", 0)),
        _line("Applications sent", stats.get("sent", 0)),
        _line("Reply rate", f"{stats.get('reply_rate', 0) * 100:.1f}%"),
        _line("Interviews and offers", stats.get("positive", 0)),
    ]

    if needs_you:
        parts += ["", "NEEDS A DECISION"]
        for item in needs_you[:8]:
            parts.append(f"  - {sanitise(str(item))}")

    if detail.get("problems"):
        parts += ["", "PROBLEMS"]
        for problem in detail["problems"][:5]:
            parts.append(f"  ! {sanitise(str(problem))}")

    dashboard = env.get("DASHBOARD_URL", "") or ""
    parts += [
        "",
        f"Open the dashboard: {dashboard}" if dashboard else "Open the dashboard to act on any of this.",
        "",
        "This note was generated by your own JobSeeker instance.",
    ]
    # Each piece of prose is cleaned on the way in, so the assembled layout is
    # left alone and the columns survive.
    return sanitise(subject), "\n".join(parts)
